version: '3'

networks:
  golang-mvc-rest-api:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:delegated
      - ./.docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - golang
      - mysql
    networks:
      - golang-mvc-rest-api

  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql:delegated
      - ./.docker/mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - golang-mvc-rest-api

  golang:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: golang
    entrypoint: ["go","run","/usr/src/app/cmd/app/main.go"]
    volumes:
      - .:/usr/src/app:delegated
    expose:
      - "8080"
    networks:
      - golang-mvc-rest-api