version: '3'

networks:
  golang-mvc-rest-api:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../.:/var/www/html:delegated
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - golang
      - mysql
    networks:
      - golang-mvc-rest-api

  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - golang-mvc-rest-api

  golang:
    build:
      context: .
      dockerfile: ./golang/Dockerfile
    container_name: golang
    volumes:
      - ../.:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - golang-mvc-rest-api